#! /bin/sh
quartus_stp -t EightThirtyTwo/tcl/832bridge.tcl 2>/dev/null >/dev/null &
while ! netstat -tna | grep 'LISTEN\>' | grep -q ':33581\>'; do
  sleep 1
done
EightThirtyTwo/832ocd/832ocd -eb -u fw/ctrl_boot_832/OSDBoot_832.bin -m fw/ctrl_boot_832/OSDBoot_832.map
kill $!
