#! /bin/sh
quartus_stp -t EightThirtyTwo/tcl/832bridge.tcl &
while ! netstat -tna | grep 'LISTEN\>' | grep -q ':33581\>'; do
  sleep 1
done
EightThirtyTwo/832ocd/832ocd -eb -m fw/ctrl_832/832OSDAB.map
kill $!
